name: Build & Publish Release APK

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Setup up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: adopt

      - name: Setup Android SDK
        run: |
          ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager "build-tools;29.0.3"

      - name: Build Release APK
        uses: gradle/gradle-command-action@v2
        with:
          arguments: assembleRelease

      - name: Get tag name
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'Splintorien/geo-nerd'
        run: |
          set -x
          echo "VERSION_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Sign APK
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'Splintorien/geo-nerd'
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Clean up, rename APK and get SHA256
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'Splintorien/geo-nerd'
        run: |
          mv app/build/outputs/apk/release/app-release-unsigned-signed.apk app/build/outputs/apk/release/geo-nerd-${VERSION_TAG}.apk
          sha=$(sha256sum app/build/outputs/apk/release/geo-nerd-${VERSION_TAG}.apk | awk '{ print $1 }')
          echo "SHA256=${sha}" >> $GITHUB_ENV

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'Splintorien/geo-nerd'
        uses: softprops/action-gh-release@v1
        with:
          files: app/build/outputs/apk/release/geo-nerd-${VERSION_TAG}.apk
          tag_name: ${{ env.VERSION_TAG }}
          name: Geo Nerd ${{ env.VERSION_TAG }}
          body: |
            ## Checksums

            | File | SHA256 |
            | ---- | ------ |
            | Standard APK | ${{ env.SHA256 }} |
          draft: true
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
